services:
  - type: web
    name: neobank-email-backend
    env: node
    buildCommand: npm run render-build
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20.20.2
      - key: EMAIL_USER
        value: bossremo665@gmail.com
      - key: EMAIL_PASS
        value: gmksfowbjmacjsot
      - key: PORT
        value: 10000
